export interface MockRestaurant {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  description: string | null;
  qrCode: string;
  createdAt: string;
  categories: MockCategory[];
}

export interface MockCategory {
  id: string;
  name: string;
  description: string | null;
  order: number;
  menuItems: MockMenuItem[];
}

export interface MockMenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string | null;
  order: number;
  ratings?: { value: number; comment?: string; createdAt?: string }[];
}

export const mockRestaurants: MockRestaurant[] = [
  {
    id: "1",
    name: "Mario's Italian Kitchen",
    slug: "marios-italian-kitchen",
    description: "Authentic Italian cuisine with traditional recipes passed down through generations.",
    logo: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400",
    qrCode: "mario-qr-123",
    createdAt: new Date().toISOString(),
    categories: [
      {
        id: "1-1",
        name: "Appetizers",
        description: "Start your meal right",
        order: 1,
        menuItems: [
          {
            id: "1-1-1",
            name: "Bruschetta",
            description: "Toasted bread topped with fresh tomatoes, basil, and garlic",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=800",
            order: 1,
          },
          {
            id: "1-1-2",
            name: "Caprese Salad",
            description: "Fresh mozzarella, tomatoes, and basil drizzled with balsamic",
            price: 10.99,
            image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
            order: 2,
          },
          {
            id: "1-1-3",
            name: "Antipasto Platter",
            description: "Assorted Italian meats, cheeses, and olives",
            price: 15.99,
            image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
            order: 3,
          },
          {
            id: "1-1-4",
            name: "Garlic Bread",
            description: "Crispy bread with garlic butter and herbs",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800",
            order: 4,
          },
          {
            id: "1-1-5",
            name: "Calamari Fritti",
            description: "Crispy fried squid rings with marinara sauce",
            price: 12.99,
            image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800",
            order: 5,
          },
          {
            id: "1-1-6",
            name: "Stuffed Mushrooms",
            description: "Mushrooms filled with cheese, herbs, and breadcrumbs",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1567113463300-102a7eb3cb26?w=800",
            order: 6,
          },
          {
            id: "1-1-7",
            name: "Prosciutto & Melon",
            description: "Thinly sliced prosciutto with fresh cantaloupe",
            price: 11.99,
            image: "https://images.unsplash.com/photo-1598515214211-89d3c73c83b8?w=800",
            order: 7,
          },
          {
            id: "1-1-8",
            name: "Minestrone Soup",
            description: "Traditional vegetable soup with pasta and beans",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
            order: 8,
          },
          {
            id: "1-1-9",
            name: "Burrata Caprese",
            description: "Creamy burrata with cherry tomatoes and pesto",
            price: 13.99,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
            order: 9,
          },
          {
            id: "1-1-10",
            name: "Arancini",
            description: "Crispy risotto balls filled with mozzarella and peas",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "1-2",
        name: "Pasta",
        description: "Handmade pasta dishes",
        order: 2,
        menuItems: [
          {
            id: "1-2-1",
            name: "Spaghetti Carbonara",
            description: "Creamy pasta with bacon, eggs, and parmesan cheese",
            price: 16.99,
            image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
            order: 1,
          },
          {
            id: "1-2-2",
            name: "Fettuccine Alfredo",
            description: "Classic creamy alfredo sauce with parmesan",
            price: 15.99,
            image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
            order: 2,
          },
          {
            id: "1-2-3",
            name: "Linguine alle Vongole",
            description: "Fresh clams in white wine sauce",
            price: 19.99,
            image: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800",
            order: 3,
          },
          {
            id: "1-2-4",
            name: "Lasagna",
            description: "Layered pasta with meat, cheese, and marinara sauce",
            price: 18.99,
            image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800",
            order: 4,
          },
          {
            id: "1-2-5",
            name: "Penne Arrabbiata",
            description: "Spicy tomato sauce with garlic and red peppers",
            price: 14.99,
            image: "https://images.unsplash.com/photo-1551462147-85895e3a59f1?w=800",
            order: 5,
          },
          {
            id: "1-2-6",
            name: "Ravioli di Ricotta",
            description: "Homemade ravioli filled with ricotta and spinach",
            price: 17.99,
            image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=800",
            order: 6,
          },
          {
            id: "1-2-7",
            name: "Spaghetti Bolognese",
            description: "Classic meat sauce with ground beef and tomatoes",
            price: 16.99,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
            order: 7,
          },
          {
            id: "1-2-8",
            name: "Gnocchi alla Sorrentina",
            description: "Potato gnocchi with tomato sauce and mozzarella",
            price: 17.99,
            image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800",
            order: 8,
          },
          {
            id: "1-2-9",
            name: "Tagliatelle al Ragu",
            description: "Fresh tagliatelle with slow-cooked meat sauce",
            price: 18.99,
            image: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800",
            order: 9,
          },
          {
            id: "1-2-10",
            name: "Risotto ai Funghi",
            description: "Creamy risotto with mixed mushrooms and parmesan",
            price: 17.99,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "1-3",
        name: "Main Courses",
        description: "Hearty Italian mains",
        order: 3,
        menuItems: [
          {
            id: "1-3-1",
            name: "Chicken Parmigiana",
            description: "Breaded chicken breast with marinara and mozzarella",
            price: 18.99,
            image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800",
            order: 1,
          },
          {
            id: "1-3-2",
            name: "Veal Marsala",
            description: "Tender veal in a rich marsala wine sauce",
            price: 24.99,
            image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800",
            order: 2,
          },
          {
            id: "1-3-3",
            name: "Osso Buco",
            description: "Braised veal shanks with vegetables and gremolata",
            price: 26.99,
            image: "https://images.unsplash.com/photo-1551782450-17144efb9c50?w=800",
            order: 3,
          },
          {
            id: "1-3-4",
            name: "Grilled Salmon",
            description: "Fresh salmon with lemon butter and capers",
            price: 22.99,
            image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800",
            order: 4,
          },
          {
            id: "1-3-5",
            name: "Eggplant Parmigiana",
            description: "Breaded eggplant layered with marinara and cheese",
            price: 16.99,
            image: "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=800",
            order: 5,
          },
          {
            id: "1-3-6",
            name: "Pork Saltimbocca",
            description: "Pork cutlets with prosciutto, sage, and white wine",
            price: 20.99,
            image: "https://images.unsplash.com/photo-1558030006-450675393462?w=800",
            order: 6,
          },
          {
            id: "1-3-7",
            name: "Beef Brasato",
            description: "Slow-braised beef in red wine with vegetables",
            price: 25.99,
            image: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=800",
            order: 7,
          },
          {
            id: "1-3-8",
            name: "Seafood Risotto",
            description: "Creamy risotto with mixed seafood and saffron",
            price: 23.99,
            image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800",
            order: 8,
          },
          {
            id: "1-3-9",
            name: "Lamb Shank",
            description: "Braised lamb shank with rosemary and red wine",
            price: 27.99,
            image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
            order: 9,
          },
          {
            id: "1-3-10",
            name: "Chicken Piccata",
            description: "Sautéed chicken with lemon, capers, and white wine",
            price: 19.99,
            image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "1-4",
        name: "Desserts",
        description: "Sweet endings",
        order: 4,
        menuItems: [
          {
            id: "1-4-1",
            name: "Tiramisu",
            description: "Classic Italian dessert with coffee and mascarpone",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
            order: 1,
          },
          {
            id: "1-4-2",
            name: "Cannoli",
            description: "Crispy shells filled with sweet ricotta",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800",
            order: 2,
          },
          {
            id: "1-4-3",
            name: "Panna Cotta",
            description: "Silky vanilla custard with berry compote",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?w=800",
            order: 3,
          },
          {
            id: "1-4-4",
            name: "Gelato",
            description: "Three scoops of house-made gelato",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
            order: 4,
          },
          {
            id: "1-4-5",
            name: "Chocolate Lava Cake",
            description: "Warm chocolate cake with molten center",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
            order: 5,
          },
          {
            id: "1-4-6",
            name: "Limoncello Cake",
            description: "Light lemon cake with limoncello glaze",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
            order: 6,
          },
          {
            id: "1-4-7",
            name: "Cannoli Siciliani",
            description: "Traditional Sicilian cannoli with pistachios",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800",
            order: 7,
          },
          {
            id: "1-4-8",
            name: "Zeppole",
            description: "Italian donuts dusted with powdered sugar",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=800",
            order: 8,
          },
          {
            id: "1-4-9",
            name: "Affogato",
            description: "Vanilla gelato with a shot of espresso",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1572441713132-51c75654db73?w=800",
            order: 9,
          },
          {
            id: "1-4-10",
            name: "Tartufo",
            description: "Chocolate and vanilla gelato covered in chocolate",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
            order: 10,
          },
        ],
      },
    ],
  },
  {
    id: "2",
    name: "Tokyo Sushi Bar",
    slug: "tokyo-sushi-bar",
    description: "Fresh sushi and Japanese cuisine made with premium ingredients.",
    logo: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400",
    qrCode: "tokyo-qr-456",
    createdAt: new Date().toISOString(),
    categories: [
      {
        id: "2-1",
        name: "Starters",
        description: "Begin your journey",
        order: 1,
        menuItems: [
          {
            id: "2-1-1",
            name: "Edamame",
            description: "Steamed soybeans with sea salt",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976?w=800",
            order: 1,
          },
          {
            id: "2-1-2",
            name: "Miso Soup",
            description: "Traditional Japanese soup with tofu and seaweed",
            price: 4.99,
            image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800",
            order: 2,
          },
          {
            id: "2-1-3",
            name: "Gyoza",
            description: "Pan-fried pork dumplings",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800",
            order: 3,
          },
          {
            id: "2-1-4",
            name: "Agedashi Tofu",
            description: "Deep-fried tofu in dashi broth",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=800",
            order: 4,
          },
          {
            id: "2-1-5",
            name: "Seaweed Salad",
            description: "Fresh seaweed with sesame dressing",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
            order: 5,
          },
          {
            id: "2-1-6",
            name: "Takoyaki",
            description: "Octopus balls with special sauce",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
            order: 6,
          },
          {
            id: "2-1-7",
            name: "Chicken Karaage",
            description: "Japanese-style fried chicken",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?w=800",
            order: 7,
          },
          {
            id: "2-1-8",
            name: "Shishito Peppers",
            description: "Blistered peppers with bonito flakes",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800",
            order: 8,
          },
          {
            id: "2-1-9",
            name: "Cucumber Salad",
            description: "Fresh cucumbers with ponzu sauce",
            price: 4.99,
            image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
            order: 9,
          },
          {
            id: "2-1-10",
            name: "Tempura Vegetables",
            description: "Lightly battered seasonal vegetables",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "2-2",
        name: "Sushi Rolls",
        description: "Traditional and creative rolls",
        order: 2,
        menuItems: [
          {
            id: "2-2-1",
            name: "California Roll",
            description: "Crab, avocado, and cucumber",
            price: 8.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 1,
          },
          {
            id: "2-2-2",
            name: "Dragon Roll",
            description: "Eel, cucumber, avocado with eel sauce",
            price: 12.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 2,
          },
          {
            id: "2-2-3",
            name: "Spicy Tuna Roll",
            description: "Fresh tuna with spicy mayo",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 3,
          },
          {
            id: "2-2-4",
            name: "Salmon Avocado Roll",
            description: "Fresh salmon and creamy avocado",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 4,
          },
          {
            id: "2-2-5",
            name: "Caterpillar Roll",
            description: "Eel and cucumber topped with avocado",
            price: 11.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 5,
          },
          {
            id: "2-2-6",
            name: "Rainbow Roll",
            description: "California roll topped with assorted fish",
            price: 13.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 6,
          },
          {
            id: "2-2-7",
            name: "Spider Roll",
            description: "Soft-shell crab, cucumber, and avocado",
            price: 12.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 7,
          },
          {
            id: "2-2-8",
            name: "Philadelphia Roll",
            description: "Smoked salmon, cream cheese, and cucumber",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 8,
          },
          {
            id: "2-2-9",
            name: "Volcano Roll",
            description: "Spicy tuna and crab with spicy sauce",
            price: 11.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 9,
          },
          {
            id: "2-2-10",
            name: "Crispy Rice Roll",
            description: "Spicy tuna on crispy rice",
            price: 10.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "2-3",
        name: "Nigiri",
        description: "Premium fish on rice",
        order: 3,
        menuItems: [
          {
            id: "2-3-1",
            name: "Salmon Nigiri",
            description: "Fresh Atlantic salmon",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 1,
          },
          {
            id: "2-3-2",
            name: "Tuna Nigiri",
            description: "Premium bluefin tuna",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 2,
          },
          {
            id: "2-3-3",
            name: "Eel Nigiri",
            description: "Grilled eel with sweet sauce",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 3,
          },
          {
            id: "2-3-4",
            name: "Yellowtail Nigiri",
            description: "Fresh yellowtail hamachi",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 4,
          },
          {
            id: "2-3-5",
            name: "Shrimp Nigiri",
            description: "Sweet cooked shrimp",
            price: 4.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 5,
          },
          {
            id: "2-3-6",
            name: "Squid Nigiri",
            description: "Fresh squid with delicate texture",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 6,
          },
          {
            id: "2-3-7",
            name: "Octopus Nigiri",
            description: "Tender octopus with wasabi",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 7,
          },
          {
            id: "2-3-8",
            name: "Sea Urchin Nigiri",
            description: "Premium uni with rich flavor",
            price: 12.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 8,
          },
          {
            id: "2-3-9",
            name: "Scallop Nigiri",
            description: "Sweet fresh scallops",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 9,
          },
          {
            id: "2-3-10",
            name: "Mackerel Nigiri",
            description: "Rich mackerel with pickled flavor",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "2-4",
        name: "Sashimi",
        description: "Fresh sliced fish",
        order: 4,
        menuItems: [
          {
            id: "2-4-1",
            name: "Sashimi Platter",
            description: "Assorted fresh fish (12 pieces)",
            price: 24.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 1,
          },
          {
            id: "2-4-2",
            name: "Salmon Sashimi",
            description: "Fresh salmon slices (5 pieces)",
            price: 12.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 2,
          },
          {
            id: "2-4-3",
            name: "Tuna Sashimi",
            description: "Premium tuna slices (5 pieces)",
            price: 14.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 3,
          },
          {
            id: "2-4-4",
            name: "Yellowtail Sashimi",
            description: "Fresh yellowtail slices (5 pieces)",
            price: 13.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 4,
          },
          {
            id: "2-4-5",
            name: "White Fish Sashimi",
            description: "Assorted white fish (5 pieces)",
            price: 11.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 5,
          },
          {
            id: "2-4-6",
            name: "Toro Sashimi",
            description: "Premium fatty tuna (3 pieces)",
            price: 19.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 6,
          },
          {
            id: "2-4-7",
            name: "Scallop Sashimi",
            description: "Fresh sweet scallops (4 pieces)",
            price: 13.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 7,
          },
          {
            id: "2-4-8",
            name: "Octopus Sashimi",
            description: "Tender octopus slices (4 pieces)",
            price: 10.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 8,
          },
          {
            id: "2-4-9",
            name: "Sea Urchin Sashimi",
            description: "Premium uni (3 pieces)",
            price: 16.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 9,
          },
          {
            id: "2-4-10",
            name: "Mixed Sashimi Deluxe",
            description: "Chef's selection of premium fish (15 pieces)",
            price: 32.99,
            image: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800",
            order: 10,
          },
        ],
      },
    ],
  },
  {
    id: "3",
    name: "Burger Palace",
    slug: "burger-palace",
    description: "Gourmet burgers made with fresh, locally sourced ingredients.",
    logo: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=400",
    qrCode: "burger-qr-789",
    createdAt: new Date().toISOString(),
    categories: [
      {
        id: "3-1",
        name: "Burgers",
        description: "Our signature burgers",
        order: 1,
        menuItems: [
          {
            id: "3-1-1",
            name: "Classic Burger",
            description: "Beef patty, lettuce, tomato, onion, pickles, special sauce",
            price: 12.99,
            image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
            order: 1,
          },
          {
            id: "3-1-2",
            name: "BBQ Bacon Burger",
            description: "Beef patty, cheddar, crispy bacon, onion rings, BBQ sauce",
            price: 15.99,
            image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800",
            order: 2,
          },
          {
            id: "3-1-3",
            name: "Veggie Burger",
            description: "House-made vegetable patty with avocado and sprouts",
            price: 11.99,
            image: "https://images.unsplash.com/photo-1525059696034-4967a7290025?w=800",
            order: 3,
          },
          {
            id: "3-1-4",
            name: "Mushroom Swiss Burger",
            description: "Beef patty with sautéed mushrooms and Swiss cheese",
            price: 14.99,
            image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800",
            order: 4,
          },
          {
            id: "3-1-5",
            name: "Double Cheeseburger",
            description: "Two beef patties with double cheese and special sauce",
            price: 16.99,
            image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800",
            order: 5,
          },
          {
            id: "3-1-6",
            name: "Chicken Burger",
            description: "Grilled chicken breast with avocado and chipotle mayo",
            price: 13.99,
            image: "https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=800",
            order: 6,
          },
          {
            id: "3-1-7",
            name: "Turkey Burger",
            description: "Lean turkey patty with cranberry sauce and arugula",
            price: 13.99,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800",
            order: 7,
          },
          {
            id: "3-1-8",
            name: "Hawaiian Burger",
            description: "Beef patty with grilled pineapple and teriyaki glaze",
            price: 14.99,
            image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800",
            order: 8,
          },
          {
            id: "3-1-9",
            name: "Jalapeño Burger",
            description: "Spicy beef patty with jalapeños, pepper jack, and chipotle",
            price: 14.99,
            image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800",
            order: 9,
          },
          {
            id: "3-1-10",
            name: "Wagyu Burger",
            description: "Premium wagyu beef with truffle aioli and arugula",
            price: 22.99,
            image: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "3-2",
        name: "Sides",
        description: "Perfect accompaniments",
        order: 2,
        menuItems: [
          {
            id: "3-2-1",
            name: "French Fries",
            description: "Crispy golden fries",
            price: 4.99,
            image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800",
            order: 1,
          },
          {
            id: "3-2-2",
            name: "Onion Rings",
            description: "Beer-battered onion rings",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
            order: 2,
          },
          {
            id: "3-2-3",
            name: "Sweet Potato Fries",
            description: "Crispy sweet potato fries",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
            order: 3,
          },
          {
            id: "3-2-4",
            name: "Loaded Fries",
            description: "Fries topped with cheese, bacon, and jalapeños",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800",
            order: 4,
          },
          {
            id: "3-2-5",
            name: "Tater Tots",
            description: "Crispy potato tots with dipping sauce",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
            order: 5,
          },
          {
            id: "3-2-6",
            name: "Coleslaw",
            description: "Fresh cabbage slaw with creamy dressing",
            price: 3.99,
            image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
            order: 6,
          },
          {
            id: "3-2-7",
            name: "Mac & Cheese",
            description: "Creamy macaroni and cheese",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=800",
            order: 7,
          },
          {
            id: "3-2-8",
            name: "Buffalo Wings",
            description: "Spicy chicken wings with blue cheese",
            price: 9.99,
            image: "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800",
            order: 8,
          },
          {
            id: "3-2-9",
            name: "Nachos",
            description: "Tortilla chips with cheese, jalapeños, and salsa",
            price: 7.99,
            image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800",
            order: 9,
          },
          {
            id: "3-2-10",
            name: "Fried Pickles",
            description: "Crispy battered pickle chips with ranch",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800",
            order: 10,
          },
        ],
      },
      {
        id: "3-3",
        name: "Shakes & Drinks",
        description: "Cool refreshments",
        order: 3,
        menuItems: [
          {
            id: "3-3-1",
            name: "Chocolate Shake",
            description: "Rich chocolate milkshake",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 1,
          },
          {
            id: "3-3-2",
            name: "Vanilla Shake",
            description: "Classic vanilla milkshake",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 2,
          },
          {
            id: "3-3-3",
            name: "Strawberry Shake",
            description: "Fresh strawberry milkshake",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 3,
          },
          {
            id: "3-3-4",
            name: "Oreo Shake",
            description: "Cookies and cream milkshake",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 4,
          },
          {
            id: "3-3-5",
            name: "Peanut Butter Shake",
            description: "Creamy peanut butter milkshake",
            price: 6.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 5,
          },
          {
            id: "3-3-6",
            name: "Soda",
            description: "Assorted soft drinks",
            price: 2.99,
            image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800",
            order: 6,
          },
          {
            id: "3-3-7",
            name: "Fresh Lemonade",
            description: "Freshly squeezed lemonade",
            price: 3.99,
            image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800",
            order: 7,
          },
          {
            id: "3-3-8",
            name: "Iced Tea",
            description: "Sweet or unsweetened iced tea",
            price: 2.99,
            image: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800",
            order: 8,
          },
          {
            id: "3-3-9",
            name: "Root Beer Float",
            description: "Root beer with vanilla ice cream",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 9,
          },
          {
            id: "3-3-10",
            name: "Banana Shake",
            description: "Creamy banana milkshake",
            price: 5.99,
            image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800",
            order: 10,
          },
        ],
      },
    ],
  },
];

export function getMockRestaurants() {
  return mockRestaurants.map(({ categories, ...rest }) => ({
    ...rest,
    _count: {
      categories: categories.length,
    },
  }));
}

export function getMockRestaurantBySlug(slug: string) {
  return mockRestaurants.find((r) => r.slug === slug);
}

export function getMockRestaurantById(id: string) {
  return mockRestaurants.find((r) => r.id === id);
}
